[host]
labels = { "central" = "wasmcloud" }
allow_latest = true

[actors]
autoupdate = true
source = "file://actors"

[providers]
capabilities = [
  "wasmcloud:couchbase",
  "wasmcloud:nats"
]

[wasmcloud]
nats_url = "nats://nats:4222"
