apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: http-hello-world
  annotations:
    description: 'Simple HTTP hello world server'
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: ghcr.io/hummusonrails/hello-world:0.2.0
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: placement
          properties:
            constraints:
              - key: role
                operator: In
                values: ["edge"]
        - type: link
          properties:
            target: keyvalue-nats
            namespace: wasi
            package: keyvalue
            interfaces: [store, atomics]
            link_name: default
            target_config:
              - name: wasi-keyvalue-config
                properties:
                  bucket: "wasmcloud"
                  enable_bucket_auto_create: "true"
                  nats_url: "nats://nats"

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.26.0
      traits:
        - type: placement
          properties:
            constraints:
              - key: role
                operator: In
                values: ["edge"]
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 0.0.0.0:8000

    - name: keyvalue-nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/keyvalue-nats:0.3.1
      traits:
        - type: placement
          properties:
            constraints:
              - key: role
                operator: In
                values: ["edge"]
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: keyvalue
            interfaces: [store, atomics]
            link_name: default
