# Use the official Codespaces base image
FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Install the wash CLI
RUN curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | sudo bash && \
    sudo apt install wash
