name: Deploy Central wasmCloud Node

on:
  push:
    branches:
      - main
    paths:
      - "central-node/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Central wasmCloud instance
        run: |
          cd central-node
          ./start.sh
